# Generated by Django 5.1.2 on 2025-07-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_avatar',
            field=models.CharField(blank=True, default='default.png', max_length=255, null=True, verbose_name='Ruta del Avatar'),
        ),
    ]
