# Generated by Django 5.1.2 on 2025-07-05 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0002_alumno_alumno_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('Tipo_ActividadId', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_ActividadDescripcion', models.TextField(verbose_name='Descripción del Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Tipo Actividad',
                'verbose_name_plural': 'Tipo Actividades',
                'ordering': ['-Tipo_ActividadId'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('Tipo_ServicioId', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_ServicioDescripcion', models.TextField(verbose_name='Descripción del Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Tipo Servicio',
                'verbose_name_plural': 'Tipo Servicios',
                'ordering': ['-Tipo_ServicioId'],
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='servicio_tipo_servicio',
        ),
        migrations.AddField(
            model_name='actividad',
            name='actividad_servicioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='api_unfrutoparacristo.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='desafiodetalle',
            name='desafiodetalle_rutAprobado',
            field=models.TextField(null=True, verbose_name='RUTs de Aprobacion (separados por coma)'),
        ),
        migrations.CreateModel(
            name='ActividadDetalle',
            fields=[
                ('ActividadDetalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('ActividadDetalle_ActividadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actividad', to='api_unfrutoparacristo.actividad', verbose_name='Actividad')),
                ('ActividadDetalle_DesafioID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Desafio', to='api_unfrutoparacristo.desafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Detalle de Actividad',
                'verbose_name_plural': 'Detalles de Actividad',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='Actividad_TipoActividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Actividad', to='api_unfrutoparacristo.tipoactividad', verbose_name='Tipo_Actividad'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicio_tiposervicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoServicio', to='api_unfrutoparacristo.tiposervicio', verbose_name='Tipo Servicio'),
        ),
    ]
