# Generated by Django 5.1.2 on 2025-07-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0003_tipoactividad_tiposervicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='cesta_doradas_puestas',
            field=models.IntegerField(default=0, verbose_name='Manzanas Doradas Puestas'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='cesta_rojas_puestas',
            field=models.IntegerField(default=0, verbose_name='Manzanas Rojas Puestas'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='cesta_total_doradas',
            field=models.IntegerField(default=0, verbose_name='Total Manzanas Doradas'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='cesta_total_rojas',
            field=models.IntegerField(default=0, verbose_name='Total Manzanas Rojas'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='cesta_total_verdes',
            field=models.IntegerField(default=0, verbose_name='Total Manzanas Verdes'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='cesta_verdes_puestas',
            field=models.IntegerField(default=0, verbose_name='Manzanas Verdes Puestas'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='clase_profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_jefe', to='api_unfrutoparacristo.profesor', verbose_name='Profesor(a) Jefe(a)'),
        ),
        migrations.CreateModel(
            name='FrutoColocado',
            fields=[
                ('frutocolocado_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=0.05)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('frutocolocado_cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frutos_colocados', to='api_unfrutoparacristo.cesta')),
                ('frutocolocado_fruto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_unfrutoparacristo.fruto')),
            ],
            options={
                'verbose_name': 'Fruto Colocado',
                'verbose_name_plural': 'Frutos Colocados',
            },
        ),
    ]
