# Generated by Django 5.1.2 on 2025-07-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0004_cesta_cesta_doradas_puestas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrutoColocado',
        ),
    ]
