# Generated by Django 5.1.2 on 2025-07-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0005_delete_frutocolocado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrutoColocado',
            fields=[
                ('frutocolocado_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('frutocolocado_cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frutos_colocados', to='api_unfrutoparacristo.cesta')),
                ('frutocolocado_fruto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_unfrutoparacristo.fruto')),
            ],
            options={
                'verbose_name': 'Fruto Colocado',
                'verbose_name_plural': 'Frutos Colocados',
            },
        ),
    ]
