# Generated by Django 5.1.2 on 2025-07-06 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0006_frutocolocado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_estado_hambre', models.IntegerField(default=100, verbose_name='Nivel de Hambre')),
                ('mascota_estado_sed', models.IntegerField(default=100, verbose_name='Nivel de Sed')),
                ('mascota_estado_sobrenombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenombre de la Mascota')),
                ('mascota_estado_last_update', models.DateTimeField(auto_now=True)),
                ('mascota_estado_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_estado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
