# Generated by Django 5.1.2 on 2025-07-09 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0007_mascotaestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_enfermedades_base',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedades de Base'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_observaciones_profesor',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_telefono_apoderado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Apoderado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_fecha_nacimiento',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='clase_profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_como_jefe', to=settings.AUTH_USER_MODEL, verbose_name='Profesor(a) Jefe(a)'),
        ),
    ]
