# Generated by Django 5.1.2 on 2025-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0009_alter_usuario_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='alumno_avatar',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_avatar',
            field=models.CharField(blank=True, default='default.png', max_length=255, null=True, verbose_name='Ruta del Avatar'),
        ),
    ]
