# Generated by Django 5.1.2 on 2025-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0010_remove_alumno_alumno_avatar_usuario_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_nombre_apoderado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Apoderado'),
        ),
    ]
