# Generated by Django 5.1.2 on 2025-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0011_alumno_alumno_nombre_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
    ]
