# Generated by Django 5.1.2 on 2025-07-13 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0012_usuario_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='frutoasignado',
            name='frutoasignado_asistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fruto_asignado', to='api_unfrutoparacristo.asistencia', verbose_name='Asistencia Relacionada'),
        ),
        migrations.CreateModel(
            name='DesafioCumplido',
            fields=[
                ('desaficump_id', models.AutoField(primary_key=True, serialize=False)),
                ('desaficump_fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cumplimiento')),
                ('desaficump_aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desafios_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('desaficump_desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='api_unfrutoparacristo.desafio', verbose_name='Desafío')),
                ('desaficump_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_cumplidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Desafío Cumplido',
                'verbose_name_plural': 'Desafíos Cumplidos',
                'unique_together': {('desaficump_usuario', 'desaficump_desafio')},
            },
        ),
        migrations.AddField(
            model_name='frutoasignado',
            name='frutoasignado_desafio_cumplido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fruto_asignado', to='api_unfrutoparacristo.desafiocumplido', verbose_name='Desafío Cumplido'),
        ),
    ]
