# Generated by Django 5.1.2 on 2025-07-13 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0013_frutoasignado_frutoasignado_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia_servicio',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='api_unfrutoparacristo.servicio', verbose_name='Servicio Relacionado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicio_profesor_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesor(a) Encargado'),
        ),
    ]
