# Generated by Django 5.1.2 on 2025-07-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0014_asistencia_asistencia_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistencia_rutAsistentes',
            field=models.TextField(default='', verbose_name='RUTs de Asistentes (separados por coma)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AsistenciaDetalle',
        ),
    ]
