# Generated by Django 5.1.2 on 2025-07-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0015_asistencia_asistencia_rutasistentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='servicio_clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api_unfrutoparacristo.clase', verbose_name='Clase Asociada'),
            preserve_default=False,
        ),
    ]
