# Generated by Django 5.1.2 on 2025-07-13 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0016_servicio_servicio_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('noticia_titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('noticia_contenido', models.TextField(verbose_name='Contenido')),
                ('noticia_imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la Imagen (Opcional)')),
                ('noticia_fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('noticia_publicada', models.BooleanField(default=True, verbose_name='¿Está publicada?')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-noticia_fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='DesafioClase',
            fields=[
                ('desafio_id', models.AutoField(primary_key=True, serialize=False)),
                ('desafio_titulo', models.CharField(max_length=200, verbose_name='Título del Desafío')),
                ('desafio_video_url', models.URLField(help_text="Pega aquí la URL 'embed' de YouTube", max_length=500, verbose_name='URL del Video')),
                ('desafio_activo', models.BooleanField(default=False, verbose_name='¿Desafío visible para los alumnos?')),
                ('desafio_clase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desafio_clase', to='api_unfrutoparacristo.clase', verbose_name='Clase Asociada')),
            ],
            options={
                'verbose_name': 'Desafío de la Clase',
                'verbose_name_plural': 'Desafíos de las Clases',
            },
        ),
    ]
