# Generated by Django 5.1.2 on 2025-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0017_noticia_desafioclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='noticia_imagen_url',
        ),
        migrations.AddField(
            model_name='noticia',
            name='noticia_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen de la Noticia (Opcional)'),
        ),
    ]
