# Generated by Django 5.1.2 on 2025-07-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0018_remove_noticia_noticia_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='noticia_clase',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si la noticia es para todas las clases.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_unfrutoparacristo.clase', verbose_name='Clase Específica (Opcional)'),
        ),
    ]
