# Generated by Django 5.2.5 on 2026-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0019_noticia_noticia_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_clases',
            field=models.ManyToManyField(blank=True, related_name='profesores_asignados', to='api_unfrutoparacristo.clase', verbose_name='Clases Asignadas'),
        ),
    ]
