# Generated by Django 5.2.5 on 2026-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0020_usuario_usuario_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafioclase',
            name='desafio_contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido del Desafío'),
        ),
    ]
