# Generated by Django 5.2.5 on 2026-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0022_alter_desafioclase_desafio_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_inventario',
            field=models.TextField(default='[]', verbose_name='Inventario de Skins y Fondos (JSON)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_monedas',
            field=models.IntegerField(default=0, verbose_name='Monedas / Puntos de Minijuegos'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumno_skin_equipada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skin/Accesorio Equipado'),
        ),
    ]
