# Generated by Django 5.2.5 on 2026-07-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_unfrutoparacristo', '0023_alumno_alumno_inventario_alumno_alumno_monedas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_logros_completados',
            field=models.JSONField(blank=True, default=list, verbose_name='Logros Completados (IDs)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_inventario',
            field=models.JSONField(blank=True, default=list, verbose_name='Inventario de Tienda (JSON)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_skin_equipada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skins Equipadas'),
        ),
    ]
